<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'dev',
  'APP_SECRET' => '71778a4bd8ee800c0c7f5d9364700b78',
  'DATABASE_URL' => 'mysql://ba4d3c7eeab4af:0c6ca0c2@eu-cdbr-west-03.cleardb.net/heroku_02fb5ee7ef6c30a?reconnect=true',
);
