<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYQOb6az\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYQOb6az/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYQOb6az.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYQOb6az\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYQOb6az\App_KernelDevDebugContainer([
    'container.build_hash' => 'YQOb6az',
    'container.build_id' => '8cf39a57',
    'container.build_time' => 1669379605,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYQOb6az');
