<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRCX0LPl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRCX0LPl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRCX0LPl.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRCX0LPl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRCX0LPl\App_KernelDevDebugContainer([
    'container.build_hash' => 'RCX0LPl',
    'container.build_id' => '301c696c',
    'container.build_time' => 1669390917,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRCX0LPl');
