<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYx6RcyZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYx6RcyZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYx6RcyZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYx6RcyZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYx6RcyZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'Yx6RcyZ',
    'container.build_id' => '264a873e',
    'container.build_time' => 1669372196,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYx6RcyZ');
